# Generated by Django 2.2.10 on 2020-03-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dislike",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="like",
            name="likes",
        ),
    ]
