# Generated by Django 2.2.10 on 2020-03-30 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_auto_20200330_1807"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={"verbose_name_plural": "likes"},
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "blog")},
        ),
    ]
