# Generated by Django 2.2.10 on 2020-03-31 08:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="body", field=models.TextField(),
        ),
    ]
