# Generated by Django 2.2.10 on 2020-03-31 12:12

import django.db.models.deletion
import mptt.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_delete_reply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name_plural": "comments"},
        ),
        migrations.AddField(
            model_name="comment",
            name="level",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.Comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="rght",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="tree_id",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together={("parent", "body")},
        ),
    ]
