# Generated by Django 2.2.10 on 2020-03-31 21:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0008_auto_20200331_1212"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dislike",
            options={"verbose_name_plural": "dislikes"},
        ),
        migrations.AlterUniqueTogether(
            name="dislike",
            unique_together={("user", "blog")},
        ),
    ]
