# Generated by Django 2.2.8 on 2020-02-21 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ParamerterTemplate",
            new_name="ParameterTemplate",
        ),
        migrations.DeleteModel(
            name="ParamerterOption",
        ),
    ]
