# Generated by Django 2.2.8 on 2020-03-06 13:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_auto_20200226_2130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
