# Generated by Django 2.2.6 on 2019-11-02 06:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("services", "0003_auto_20191101_2217")]

    operations = [
        migrations.AddField(
            model_name="request",
            name="name",
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="attached_files",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), default=list, size=5
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "order started"),
                    ("canceled", "order canceled"),
                    ("delivered", "order delivered"),
                    ("accepted", "order accepted"),
                    ("completed", "order completed"),
                ],
                default="started",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
