# Generated by Django 2.2.8 on 2020-03-06 13:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_auto_20200306_1332"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="api_endpoint",
            field=models.CharField(
                default="https://sandbox.zamzar.com/v1/jobs", max_length=150
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
