# Generated by Django 2.2.6 on 2019-11-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("services", "0004_auto_20191102_0628")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.Service",
            ),
        )
    ]
