# Generated by Django 2.2.10 on 2020-03-30 13:24

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_auto_20200316_0927"),
    ]

    operations = [
        migrations.RemoveField(model_name="gallery", name="service",),
        migrations.AddField(
            model_name="service",
            name="gallery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.Gallery",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
