# Generated by Django 2.2.8 on 2020-03-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact", old_name="name", new_name="full_name",
        ),
        migrations.RenameField(
            model_name="contact", old_name="title", new_name="subject",
        ),
    ]
