- repo: local
  hooks:
      - id: isort
        name: sort imports
        language: system
        entry: 'isort -rc -y -sl'
      - id: black
        name: black
        language: system
        entry: black
        types: [python]
      - id: flake8
        name: flake8
        language: system
        entry: flake8
        types: [python]
