# Generated by Django 2.2.10 on 2020-05-07 09:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
