# Generated by Django 2.2.10 on 2020-07-25 13:50

import django.db.models.deletion
from django.db import migrations
from django.db import models

import quexl.helpers.fancy_generator


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_auto_20200725_1203"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaypalPayment",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=quexl.helpers.fancy_generator.fancy_id_generator,
                        editable=False,
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("paypal_id", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.Order",
                    ),
                ),
            ],
        ),
    ]
