# Generated by Django 2.2.6 on 2019-10-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="user", name="date_of_joining"),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
