# Generated by Django 2.2.6 on 2019-10-28 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("profiles", "0001_initial")]

    operations = [
        migrations.AlterUniqueTogether(
            name="language", unique_together={("profile", "name")}
        )
    ]
