# Generated by Django 2.2.6 on 2019-11-27 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quexl.helpers.fancy_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D", "Delivered"),
                            ("UR", "Unread"),
                            ("R", "Read"),
                        ],
                        default="D",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_message",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=30)),
                (
                    "participants",
                    models.ManyToManyField(
                        through="messaging.Participant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="participant",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="messaging.Thread",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=quexl.helpers.fancy_generator.fancy_id_generator,
                        editable=False,
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(max_length=255)),
                (
                    "sent_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messaging.Thread",
                    ),
                ),
            ],
        ),
    ]
