# Generated by Django 2.2.6 on 2019-12-02 12:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("messaging", "0002_auto_20191202_1201")]

    operations = [
        migrations.AddField(
            model_name="message",
            name="msg_status",
            field=models.CharField(default="S", max_length=5),
        ),
        migrations.AlterField(
            model_name="participant",
            name="message_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D", "Delivered"),
                    ("UR", "Unread"),
                    ("R", "Read"),
                    ("S", "Sent"),
                ],
                default="D",
                max_length=20,
            ),
        ),
    ]
