# Generated by Django 2.2.6 on 2019-12-05 10:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("messaging", "0003_auto_20191202_1204")]

    operations = [
        migrations.AlterModelOptions(
            name="message", options={"ordering": ("-sent_at",)}
        ),
        migrations.AlterModelOptions(
            name="thread", options={"ordering": ("-last_message",)}
        ),
        migrations.AddField(
            model_name="thread",
            name="type",
            field=models.CharField(default="dm", max_length=20),
            preserve_default=False,
        ),
    ]
