name: Django application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: quexl
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev
    - name: Setup Redis 5
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '5.x'
    - name: Install dependencies
      run: |
        # install libv to prevent psycopg2 build errors
        sudo apt-get update && sudo apt-get install libpq-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with black
      run: |
        black --check quexl
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        EXTERNAL_API_KEY: ${{ secrets.EXTERNAL_API_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: pytest
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
